language: node_js
dist: focal
jobs:
  include:
    - name: "JavaScript driver"
      node_js: "10"
      services:
        - postgresql
      addons:
        postgresql: "12"
      script:
        - psql --version
        - pg_isready
        - ls -lah /etc/postgresql/12
        - rm -fr ./node_modules
        - hash -r
        - npm install
        - npm run build
        - npm run test
        - nyc report --reporter=text-lcov | coveralls
        - nyc check-coverage --lines 50
after_success:
  - npm run lint
  - NODE_ENV=test nyc npm run test
  - nyc report --reporter=text-lcov | coveralls
  - npm run build
  - semantic-release
notifications:
  email: false
sudo: false
